### ISSUE TITLE
Possibly unclean threads termination

### ISSUE THREAD

**Issue by qrilka** [scrapinghub/crawlera-tools#3]
Alain Quenneville seen the following exception (running python 2.7.3 on Linux Ubuntu 12.04.3 LTS):

```
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 504, in run
  File "./crawlera-bench", line 30, in worker_request
  File "/usr/lib/python2.7/Queue.py", line 168, in get
  File "/usr/lib/python2.7/threading.py", line 236, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

probably it comes from the fact that worker threads are demonized

**Comment by pawelmhm** [comment]
one thing I noticed is that we exit using [os._exit(1)](https://github.com/scrapinghub/crawlera-tools/blob/master/crawlera-bench#L71)

> os._exit(n)
> Exit the process with status n, without calling cleanup handlers, flushing stdio buffers, etc.

[docs](https://docs.python.org/2/library/os.html)

I stumbled on some issues with bench when running crawlera benchmarks that take bit longer, seems like fab task using crawlera bench gets stuck. I think there are two problems here first of all exiting with 1 means that we're exiting with error on unix, this means that fab or any other script that relies on exit codes is getting confused. Secondly we're not doing any kind of cleanup of all those threads that are running, we just interrupt whole thing in the middle. 

As the code is currently written it seems difficult to refactor all this so that it stops when it should. Perhaps we could just migrate script to async library? e.g. gevents? It would give us same performance but without problems related to threads.
